# Generated by Django 4.2.2 on 2025-11-18 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_carvariants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carvariants',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_variants', to='product.car'),
        ),
    ]
