# Generated by Django 4.2.2 on 2025-11-18 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_carimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarImage',
        ),
    ]
