# Generated by Django 4.2.2 on 2025-11-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_cartitems_car_color_cartitems_car_engine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='car_price',
            field=models.IntegerField(default=0),
        ),
    ]
