# Generated by Django 4.2.2 on 2025-11-23 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_cart_is_paid_orderitems_order_cart_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='is_paid',
            new_name='is_order',
        ),
    ]
