# Generated by Django 4.2.2 on 2025-11-23 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_order_created_at_alter_order_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Scheduled', 'Scheduled'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Accepted', max_length=50),
        ),
    ]
